Added base of infra and backend + Added base of minio-service
Pepelulka-Inc/animeshki pull request #16
Opened 2024-11-23 19:36 UTC by pepelulka

2024-11-23 20:06 UTC, L0ckR requested changes
Сделай HOST port в переменную окружения и пропиши в compose и батниках возможность его менять

2024-11-23 21:23 UTC, kumaroid commented on animeshki-backend/src/minio-service/app/connection.py
> +import logging
давай будем использовать асинхронный логгер
https://aiologger.readthedocs.io/en/latest/README.html

2024-11-23 21:23 UTC, kumaroid commented on animeshki-backend/src/minio-service/app/handlers.py
> +import logging
тоже самое с aiologger

2024-11-23 21:23 UTC, kumaroid commented on animeshki-backend/src/minio-service/requirements.txt
> +aiohttp
давай явно указывать версии библиотек? например: aiohttp=3.11.7  или aiohttp>=*****(используемая версия)

2024-11-23 21:23 UTC, kumaroid commented on animeshki-backend/src/minio-service/app/handlers.py
> +            await response.write_eof()  # Конец записи файла
думаю, можно добавить некий менеджер статуса файлов типа
```python
from enum import Enum
from attr import dataclass, field, validators

class FileStatus(Enum):
    PENDING_UPLOAD = "PendingUpload"
    IN_PROGRESS = "InProgress"
    LOADED = "Loaded"
    SUCCESS = "Success"
    FAILED = "Failed"
    
@dataclass(slots=True)
class File:
    name: str
    path: str
    _status: FileStatus
    last_modified: datetime = field(validator=valiators.instance_of(datetime))
    
    @property
    def status(self) -> FileStatus:
        return self._status
        
    def pending_upload(self):
        self._status = FileStatus.PENDING_UPLOAD
        
    def in_progress(self):
        self._status = FileStatus.IN_PROGRESS
        
    def loaded(self):
        self._status = FileStatus.LOADED
        
    def success(self):
        self._status = FileStatus.SUCCESS
        
    def failed(self):
        self._status = FileStatus.FAILED

2024-11-24 10:30 UTC, kumaroid commented on animeshki-backend/src/minio-service/app/handlers.py
> +            await response.write_eof()  # Конец записи файла
забиваем на aiologger, он не поддерживает python > 3.10

2024-11-24 10:52 UTC, pepelulka commented on animeshki-backend/src/minio-service/app/handlers.py
> +            await response.write_eof()  # Конец записи файла
Добро

2024-11-25 08:19 UTC, kumaroid approved these changes

2024-11-25 08:19 UTC, merged