added database utils and auth
Pepelulka-Inc/animeshki pull request #26
Opened 2024-12-22 20:47 UTC by kumaroid

МВП(!!!!)
Допишу докер в ближайшее время
Нужно продумать 2 вещи - как выдавать пользователю роль(отдельная ручка или как то руками в бд, но логика реализована, роли 'admin' и 'user')
Второе - подумать насчет валидации пароля, хотя санек вроде там на фронте валидировать собрался так что пофиг(?)

2024-12-23 11:33 UTC, pepelulka requested changes

2024-12-23 11:33 UTC, pepelulka commented on animeshki-backend/src/animeshki/auth.py
> +ACCESS_TOKEN_EXPIRE_DAYS = 30
В чем смысл делать expire время access и refresh токена одинаковыми? От этого весь их смысл теряется + обычно время жизни access token'а делают порядка 15 минут, уж точно не 30 дней.

2024-12-23 11:33 UTC, pepelulka commented on animeshki-backend/src/animeshki/auth.py
> +            username = data["username"]
Почему тут проверка имени пользователя? Права должны же проверяться по jwt токену, который приходит

2024-12-23 11:33 UTC, pepelulka commented on animeshki-backend/src/animeshki/auth.py
> +            username = data["username"]
Плюс эта функция должна быть доступна всем сервисам, которые хотят проверять авторизацию пользователей, надо бы ее вынести куда то в общий доступ (хотя бы для фронтенда чтобы она была доступна, как я понимаю именно он будет осуществлять проверку авторизации, а другие сервисы уже будет ему доверять)

2024-12-23 11:33 UTC, pepelulka commented on animeshki-backend/src/animeshki/auth.py
> +        print(user_data)
Одинокий потерявшийся принт

2024-12-23 11:33 UTC, pepelulka commented on animeshki-backend/src/animeshki/auth.py
> +@check_credentials_admin("admin")
почему рефрешнуть токен может только админ?

2024-12-23 11:33 UTC, pepelulka commented on animeshki-backend/src/animeshki/auth.py
> +        return web.json_response(
Почему нет никакой проверки на то, что срок жизни refresh_token истёк?

2024-12-23 12:43 UTC, pepelulka requested changes

2024-12-23 12:43 UTC, pepelulka commented on animeshki-backend/src/animeshki/infrastructure/database/models.py
> +    id = Column(Integer, primary_key=True, index=True)
Это че за уебок остался, зачем нам id если у нас есть anime_id

2024-12-23 12:43 UTC, pepelulka commented on animeshki-backend/src/animeshki/infrastructure/database/models.py
> +    users_started_num = Column(Integer, index=True)
а зачем users_started_num и users_completed_num делать индексами? по ним же вообще поиска не будет точно

2024-12-23 13:21 UTC, kumaroid commented on animeshki-backend/src/animeshki/infrastructure/database/models.py
> +    id = Column(Integer, primary_key=True, index=True)
у нас в диаграмме айди остался, поменяй там тоже пж

2024-12-23 13:33 UTC, merged

2024-12-26 21:39 UTC, L0ckR commented on animeshki-backend/src/animeshki/infrastructure/database/models.py
> +    users_started_num = Column(Integer, index=True)
resolved in [remove id and indexes](https://github.com/Pepelulka-Inc/animeshki/pull/26/commits/6e3c5a8184785e837b5be1d195309e779caf59ad)

2024-12-26 21:39 UTC, L0ckR commented on animeshki-backend/src/animeshki/infrastructure/database/models.py
> +    id = Column(Integer, primary_key=True, index=True)
resolved in [remove id and indexes](https://github.com/Pepelulka-Inc/animeshki/pull/26/commits/6e3c5a8184785e837b5be1d195309e779caf59ad)